### Create team
PUT localhost:8080/teams/api/v1/3568a2f2-5c83-41f5-92d9-8b9f10108426
Content-Type: application/json

{
  "sourceTeamId":"01fdbce4-7d10-4916-b71f-13cf61bbffe8"
}

### Get default teams
GET localhost:8080/teams/api/v1

### Get team
GET localhost:8080/teams/api/v1/01fdbce4-7d10-4916-b71f-13cf61bbffe8

### Get LineUp
GET localhost:8080/teams/api/v1/01fdbce4-7d10-4916-b71f-13cf61bbffe8/lineup

### Get team squad
GET localhost:8080/teams/api/v1/01fdbce4-7d10-4916-b71f-13cf61bbffe8/squad
